services:
  main-server:
    image: nginx:stable
    ports:
      - 8050:8050
    volumes:
      - ./static:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
  server-one:
    image: nginx:stable
    ports:
      - 8051:8051
    volumes:
      - ./static:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
  server-two:
    image: nginx:stable
    ports:
      - 8052:8052
    volumes:
      - ./static:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
