version: '3'

services:
  main-server:
    build:
      context: ./
    ports:
      - 8050:8050
  server-one:
    build:
      context: ./server-one
    ports:
      - 8051:8051
  server-two:
    build:
      context: ./server-two
    ports:
      - 8052:8052
